apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s: 
      retention: 24h
      volumeClaimTemplate:
       spec:
         storageClassName: odf-lvm-vg1
         volumeMode: Filesystem
         resources:
           requests:
             storage: 40Gi
